name: CI

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.19.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Test
        run: go test -race

